# KoVibes API workflow

name: KoVibes-CI

# Controls when the workflow is triggered
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # Build the project
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build
        run: ./gradlew kovibes:build

  #Check code coverage
  code-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Run kover
        run: ./gradlew kovibes:koverXmlReport
      - name: Verify code coverage
        run: ./gradlew kovibes:koverVerify
      - name: Print code coverage
        run: ./gradlew kovibes:koverLog
#      - name: Upload report
#        uses: codecov/codecov-action@v4.0.1
#        with:
#          token: ${{ secrets.CODECOV_TOKEN }}
#          slug: rubenquadros/Kotlin-Spotify-Api
#          files: core/build/reports/kover/report.xml
#        continue-on-error: false
